version: 0.2

env:
  variables:
    IMAGE_NAME: flask-hello-world
  parameter-store:
    DOCKERHUB_USERNAME: /myapp/docker-credentials/username
    DOCKERHUB_PASSWORD: /myapp/docker-credentials/password

phases:
  install:
    commands:
      - echo Logging in to Docker Hub...
      - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $DOCKERHUB_USERNAME/$IMAGE_NAME:latest -f app/Dockerfile app/

  post_build:
    commands:
      - echo Pushing the image to Docker Hub...
      - docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:latest
