version: 0.2

env:
  variables:
    IMAGE_NAME: flask-hello-world
  parameter-store:
    DOCKERHUB_USERNAME: /myapp/docker-credentials/username
    DOCKERHUB_PASSWORD: /myapp/docker-credentials/password

phases:
  install:
    commands:
      - echo Logging in to Docker Hub...
      - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

  pre_build:
    commands:
      - echo Setting image tag...
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - echo IMAGE_TAG=$IMAGE_TAG
      - echo "IMAGE_TAG=$IMAGE_TAG" >> build.properties

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $DOCKERHUB_USERNAME/$IMAGE_NAME:$IMAGE_TAG -f app/Dockerfile app/

  post_build:
    commands:
      - echo Pushing the Docker image with tag $IMAGE_TAG...
      - docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:$IMAGE_TAG

artifacts:
  files:
    - build.properties
